# Generated by Django 5.0 on 2023-12-31 08:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fictionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='title',
        ),
        migrations.AddField(
            model_name='hero',
            name='birth_date',
            field=models.DateField(default=datetime.date(2020, 6, 8)),
        ),
        migrations.AddField(
            model_name='hero',
            name='cinema_debut',
            field=models.DateTimeField(default=datetime.date(2020, 6, 8)),
        ),
        migrations.AddField(
            model_name='hero',
            name='civilian_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='hero',
            name='email',
            field=models.CharField(default='default@example.com', max_length=255, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
