# Generated by Django 5.0 on 2023-12-31 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fictionapp', '0002_remove_hero_publication_date_remove_hero_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='name',
            field=models.CharField(choices=[('DC', 'DC'), ('Marvel', 'Marvel'), ('Anime', 'Anime'), ('Live Action', 'Live Action')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cinema_debut',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 0, 0)),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Villain', 'Villain'), ('Hero', 'Hero'), ('Antihero', 'Antihero')], max_length=50),
        ),
    ]
