# Generated by Django 5.0 on 2023-12-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fictionapp', '0003_alter_comic_name_alter_hero_cinema_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Avengers', 'Avengers'), ('Justice League', 'Justice League')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
