# Generated by Django 5.0 on 2023-12-31 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fictionapp', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fictionapp.team'),
        ),
    ]
