# Generated by Django 5.0 on 2023-12-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fictionapp', '0006_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('Avengers', 'Avengers'), ('Justice League', 'Justice League')], max_length=50, null=True),
        ),
    ]
