# Generated by Django 5.0 on 2023-12-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fictionapp', '0010_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='sex',
            field=models.ManyToManyField(to='fictionapp.sex'),
        ),
    ]
